version: "2.0"
services:
  web:
    build: .
    ports:
      - "80:80"
    environment:
      PORT: 80
    depends_on:
      - mongo
      - rabbit
  mongo:
    image: "mongo:4.2.8"
    ports:
      - "27017:27017"
  rabbit:
    image: "rabbitmq:3-management"
    ports:
      - "5672:5672"
      - "15672:15672"
